# This file is auto-generated by packaging/homebrew/generate_formula.sh on release.
# Do not edit by hand -- changes will be overwritten on the next tag.
class CodeanalyzerTypescript < Formula
  desc "CLDK TypeScript analyzer (cants) -- emits canonical CLDK analysis.json"
  homepage "https://github.com/codellm-devkit/codeanalyzer-typescript"
  version "1.6.1"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/codellm-devkit/codeanalyzer-typescript/releases/download/v1.6.1/cants-macosx_11_0_arm64"
      sha256 "adffb2fb144a6d5aadd9b78afa5748c75d0b00a7f75f0756d25e93ef033967bc"
    end
    on_intel do
      url "https://github.com/codellm-devkit/codeanalyzer-typescript/releases/download/v1.6.1/cants-macosx_10_12_x86_64"
      sha256 "024ea43f286346bffe6191ae8b2aae9b53ba91d3956260efa2ed7c2cf55c459a"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/codellm-devkit/codeanalyzer-typescript/releases/download/v1.6.1/cants-manylinux2014_aarch64"
      sha256 "75df562b9c7ef6485b246c97018774bd7587b7b7b0bea9b2d968fe1ce710e606"
    end
    on_intel do
      url "https://github.com/codellm-devkit/codeanalyzer-typescript/releases/download/v1.6.1/cants-manylinux2014_x86_64"
      sha256 "e01c91e55cd4a9d0000afea27c7c5c845da56b5ec8d894910e781e500b6ddc79"
    end
  end

  def install
    # The release asset is a bare executable; Homebrew stages it under its
    # original (platform-tagged) name. Install it as the canonical "cants".
    bin.install Dir["cants-*"].first => "cants"
  end

  test do
    # cants has no --version flag and requires -i; --help is handled first and
    # exits 0, so it is the safe smoke test that the binary runs on this platform.
    assert_match "Usage: cants", shell_output("#{bin}/cants --help")
  end
end
