# This file is auto-generated by packaging/homebrew/generate_formula.sh on release.
# Do not edit by hand -- changes will be overwritten on the next tag.
class CodeanalyzerTypescript < Formula
  desc "CLDK TypeScript analyzer (cants) -- emits canonical CLDK analysis.json"
  homepage "https://github.com/codellm-devkit/codeanalyzer-typescript"
  version "1.6.0"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/codellm-devkit/codeanalyzer-typescript/releases/download/v1.6.0/cants-macosx_11_0_arm64"
      sha256 "664793b344e3461be0ca1f67da6351c1f3e61743bbe15c1b01dd2b3da0bc3fe0"
    end
    on_intel do
      url "https://github.com/codellm-devkit/codeanalyzer-typescript/releases/download/v1.6.0/cants-macosx_10_12_x86_64"
      sha256 "fd89b13ea859f2fee6997d8b38892c59812b178aa353b9222495bee227f35ec3"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/codellm-devkit/codeanalyzer-typescript/releases/download/v1.6.0/cants-manylinux2014_aarch64"
      sha256 "eb88e90e15e117ca71a9d494d442b5c4b3fa0bba597a9a1393826f7239adf10c"
    end
    on_intel do
      url "https://github.com/codellm-devkit/codeanalyzer-typescript/releases/download/v1.6.0/cants-manylinux2014_x86_64"
      sha256 "9631f41344bce836c53d348370eee9302226abec91552d88b7f66f1df5167444"
    end
  end

  def install
    # The release asset is a bare executable; Homebrew stages it under its
    # original (platform-tagged) name. Install it as the canonical "cants".
    bin.install Dir["cants-*"].first => "cants"
  end

  test do
    # cants has no --version flag and requires -i; --help is handled first and
    # exits 0, so it is the safe smoke test that the binary runs on this platform.
    assert_match "Usage: cants", shell_output("#{bin}/cants --help")
  end
end
