# This file is auto-generated by packaging/homebrew/generate_formula.sh on release.
# Do not edit by hand -- changes will be overwritten on the next tag.
class CodeanalyzerPython < Formula
  desc "CLDK Python analyzer (canpy) -- emits canonical analysis.json or a Neo4j graph"
  homepage "https://github.com/codellm-devkit/codeanalyzer-python"
  url "https://github.com/codellm-devkit/codeanalyzer-python/releases/download/v1.5.1/codeanalyzer_python-1.5.1.tar.gz"
  sha256 "8b7468acc2a1c079ba09b626be5947c8fc3075093cab47b5ff1a28d0a817fc43"
  version "1.5.1"
  license "Apache-2.0"

  # codeanalyzer-python is a pure-Python PyPI package with a heavy native dep
  # (ray). Rather than vendor every transitive dependency as a
  # Homebrew resource, install the pinned PyPI release as an isolated uv tool;
  # uv resolves and caches the environment on first run.
  depends_on "uv"

  def install
    %w[canpy codeanalyzer].each do |exe|
      (bin/exe).write <<~SH
        #!/bin/bash
        exec uvx --from "codeanalyzer-python==#{version}" #{exe} "$@"
      SH
      chmod 0755, bin/exe
    end
  end

  test do
    assert_match "codeanalyzer-python==#{version}", File.read(bin/"canpy")
    assert_predicate bin/"canpy", :executable?
  end
end
