# Auto-generated by codeanalyzer-java's release workflow; do not edit by hand.
class CodeanalyzerJava < Formula
  desc "CLDK Java analyzer (canjv), with a bundled JVM"
  homepage "https://github.com/codellm-devkit/codeanalyzer-java"
  url "https://files.pythonhosted.org/packages/87/53/0b87d90199855a0ce913cfca66ff3ded023f6e8ddc01f1d07db3fb1214d7/codeanalyzer_java-3.0.2-py3-none-any.whl", using: :nounzip
  sha256 "c9cf7e1fd3eb7c276ddddd832fddd75a48a3e1230abac6d869b986c472e1a7d7"
  version "3.0.2"
  license "Apache-2.0"

  depends_on "uv"

  # Resolve the wheel and its platform-specific jdk4py runtime on first use,
  # outside Homebrew's build-time network sandbox (same pattern as canpy).
  def install
    (bin/"canjv").write <<~SH
      #!/bin/bash
      exec "#{Formula["uv"].opt_bin}/uvx" --from "codeanalyzer-java==#{version}" canjv "$@"
    SH
    chmod 0755, bin/"canjv"
  end

  def caveats
    <<~EOS
      The first canjv invocation downloads the pinned PyPI package and its
      bundled JVM through uv. Internet access is required on first use.
    EOS
  end

  test do
    assert_match "codeanalyzer-java==#{version}", File.read(bin/"canjv")
    assert_predicate bin/"canjv", :executable?
  end
end
