# This file is auto-generated by packaging/homebrew/generate_formula.sh on release.
# Do not edit by hand -- changes will be overwritten on the next tag.
class CodeanalyzerIac < Formula
  desc "CLDK infrastructure-as-code analyzer (caniac) -- emits canonical CLDK analysis.json"
  homepage "https://github.com/codellm-devkit/codeanalyzer-iac"
  version "0.1.0"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/codellm-devkit/codeanalyzer-iac/releases/download/v0.1.0/caniac-macosx_11_0_arm64"
      sha256 "4184e3df22c64d5676eb30890a29ffccc1858df6ebe1eeefe02637fca66ca9f4"
    end
    on_intel do
      url "https://github.com/codellm-devkit/codeanalyzer-iac/releases/download/v0.1.0/caniac-macosx_11_0_x86_64"
      sha256 "997d09d442a7c8bf3daa48ba6909a22ca44c0b430afc413d6b09347b2d8e431b"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/codellm-devkit/codeanalyzer-iac/releases/download/v0.1.0/caniac-manylinux_2_17_aarch64"
      sha256 "b9206dd900935ca05784d693703d4b95eca8486088f50de02feee9ae6739ce78"
    end
    on_intel do
      url "https://github.com/codellm-devkit/codeanalyzer-iac/releases/download/v0.1.0/caniac-manylinux_2_17_x86_64"
      sha256 "74092981b4e40d1ca4a81b140edf98533a1d2071b929787154151c4e4d55234b"
    end
  end

  def install
    # The release asset is a bare executable; Homebrew stages it under its
    # original (platform-tagged) name. Install it as the canonical "caniac".
    bin.install Dir["caniac-*"].first => "caniac"
  end

  test do
    # caniac --version prints "caniac version <v>", the same string it stamps on
    # analyzer.version in every analysis document.
    assert_match "caniac version #{version}", shell_output("#{bin}/caniac --version")
  end
end
