# This file is auto-generated by packaging/homebrew/generate_formula.sh on release.
# Do not edit by hand -- changes will be overwritten on the next tag.
class CodeanalyzerPython < Formula
  desc "CLDK Python analyzer (canpy) -- emits canonical analysis.json or a Neo4j graph"
  homepage "https://github.com/codellm-devkit/codeanalyzer-python"
  url "https://github.com/codellm-devkit/codeanalyzer-python/releases/download/v1.0.3/codeanalyzer_python-1.0.3.tar.gz"
  sha256 "122e0e5044fd5b337d90a3a42b451168df3385c045b0faeea40b704509de11da"
  version "1.0.3"
  license "Apache-2.0"

  # codeanalyzer-python is a pure-Python PyPI package with heavy native deps
  # (ray, pandas, numpy). Rather than vendor every transitive dependency as a
  # Homebrew resource, install the pinned PyPI release as an isolated uv tool;
  # uv resolves and caches the environment on first run.
  depends_on "uv"

  def install
    %w[canpy codeanalyzer].each do |exe|
      (bin/exe).write <<~SH
        #!/bin/bash
        exec uvx --from "codeanalyzer-python==#{version}" #{exe} "$@"
      SH
      chmod 0755, bin/exe
    end
  end

  test do
    assert_match "codeanalyzer-python==#{version}", File.read(bin/"canpy")
    assert_predicate bin/"canpy", :executable?
  end
end
